// File generated by FlutterFire CLI.
// DO NOT EDIT MANUALLY.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for linux - '
            'you can re-run this by running `flutterfire configure`.');
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your-android-api-key',
    appId: 'your-android-app-id',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'book-application-app-2',
    storageBucket: 'your-storage-bucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl-5W2nM5hc5hJGfmzVRiZKhr3lV5Odpo',
    appId: '1:786312443932:ios:8fdfe4189943c999e607d9',
    messagingSenderId: '786312443932',
    projectId: 'book-application-app-2',
    storageBucket: 'book-application-app-2.firebasestorage.app',
    iosBundleId: 'com.example.bookManagementApp2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-web-api-key',
    appId: 'your-web-app-id',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'book-application-app-2',
    authDomain: 'your-auth-domain',
    storageBucket: 'your-storage-bucket',
    measurementId: 'your-measurement-id',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl-5W2nM5hc5hJGfmzVRiZKhr3lV5Odpo',
    appId: '1:786312443932:ios:8fdfe4189943c999e607d9',
    messagingSenderId: '786312443932',
    projectId: 'book-application-app-2',
    storageBucket: 'book-application-app-2.firebasestorage.app',
    iosBundleId: 'com.example.bookManagementApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCepq_Dney7sfesKUCUZWcOJagBr8L-I-w',
    appId: '1:786312443932:web:f5c3917c4bcc5055e607d9',
    messagingSenderId: '786312443932',
    projectId: 'book-application-app-2',
    authDomain: 'book-application-app-2.firebaseapp.com',
    storageBucket: 'book-application-app-2.firebasestorage.app',
    measurementId: 'G-WQMNKCN3R3',
  );

}