name: book_management_app_2
description: A book management system with Firebase integration.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.5.0
  flutter_pdfview: ^1.3.2
  path_provider: ^2.2.0
  http: ^1.3.0
  provider: ^6.2.0
  cupertino_icons: ^1.0.9
  js: ^0.8.0
  web: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true