name: book_management_app_2
description: A book management system with Firebase integration.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.0
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_pdfviewer: ^26.2.7
  path_provider: ^2.1.5
  http: ^1.2.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true