name: book_management_app_2
description: A book management system with Firebase integration.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_pdfviewer: ^27.1.53 # Reverted to 27.1.53
  path_provider: ^2.1.5
  http: ^1.2.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  js: ^0.7.1
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true